#!/usr/bin/env python3
"""claude-review: Claude Code sub-agent for PR review.

Usage:
    python3 claude-review.py --pr https://github.com/owner/repo/pull/123
    python3 claude-review.py --pr owner/repo/123

Environment:
    ANTHROPIC_API_KEY: Required for Claude API calls
    GITHUB_TOKEN: Required for fetching PR data
"""

import argparse
import json
import os
import re
import sys
from urllib.parse import urlparse

import requests


def parse_pr_url(url):
    """Parse PR URL into owner, repo, pr_number."""
    # Handle full URL or short form
    patterns = [
        r"github\.com/([^/]+)/([^/]+)/pull/(\d+)",
        r"^([^/]+)/([^/]+)/(\d+)$",
        r"^([^/]+)/([^/]+)#(\d+)$",
    ]
    
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            return match.group(1), match.group(2), match.group(3)
    
    raise ValueError(f"Could not parse PR URL: {url}")


def fetch_pr_data(owner, repo, pr_number, github_token):
    """Fetch PR data from GitHub API."""
    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    # Fetch PR details
    pr_url = f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}"
    pr_resp = requests.get(pr_url, headers=headers)
    pr_resp.raise_for_status()
    pr_data = pr_resp.json()
    
    # Fetch diff
    diff_headers = headers.copy()
    diff_headers["Accept"] = "application/vnd.github.v3.diff"
    diff_resp = requests.get(pr_url, headers=diff_headers)
    diff_resp.raise_for_status()
    
    return {
        "title": pr_data["title"],
        "body": pr_data["body"] or "",
        "author": pr_data["user"]["login"],
        "additions": pr_data["additions"],
        "deletions": pr_data["deletions"],
        "changed_files": pr_data["changed_files"],
        "diff": diff_resp.text,
        "url": pr_data["html_url"]
    }


def analyze_with_claude(pr_data, api_key):
    """Analyze PR diff using Claude API."""
    
    # Prepare the prompt
    prompt = f"""You are a code reviewer analyzing a GitHub Pull Request. Review the following PR and provide a structured analysis.

PR Title: {pr_data['title']}
Author: {pr_data['author']}
Files Changed: {pr_data['changed_files']}
Additions: +{pr_data['additions']}, Deletions: -{pr_data['deletions']}

PR Description:
{pr_data['body'][:500] if pr_data['body'] else 'No description provided'}

Diff:
```diff
{pr_data['diff'][:8000]}
```

Please provide a structured review in the following format:

## Summary
[2-3 sentences summarizing what this PR does and its impact]

## Risks
- [List any potential risks, bugs, or issues you identify]
- [Include security concerns if any]
- [Note any breaking changes]

## Suggestions
- [Specific, actionable improvements]
- [Code quality recommendations]
- [Performance considerations]

## Confidence Score
[Choose ONE: Low / Medium / High]

Guidelines for confidence:
- High: Clear, well-tested changes with no obvious issues
- Medium: Some concerns or complexity that needs attention
- Low: Significant risks, unclear implementation, or potential bugs
"""

    response = requests.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": api_key,
            "Content-Type": "application/json",
            "anthropic-version": "2023-06-01"
        },
        json={
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 2000,
            "messages": [{"role": "user", "content": prompt}]
        }
    )
    
    response.raise_for_status()
    return response.json()["content"][0]["text"]


def format_review(claude_output, pr_url):
    """Format the review as a GitHub comment."""
    return f"""## 🤖 Automated PR Review

{claude_output}

---
*This review was generated by [claude-review](https://github.com/claude-builders-bounty/claude-builders-bounty)*
*Reviewing: {pr_url}*
"""


def main():
    parser = argparse.ArgumentParser(description="Review a GitHub PR using Claude")
    parser.add_argument("--pr", required=True, help="PR URL (https://github.com/owner/repo/pull/123 or owner/repo/123)")
    parser.add_argument("--output", "-o", help="Output file (default: print to stdout)")
    args = parser.parse_args()
    
    # Check environment variables
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    github_token = os.environ.get("GITHUB_TOKEN")
    
    if not api_key:
        print("Error: ANTHROPIC_API_KEY environment variable required", file=sys.stderr)
        sys.exit(1)
    
    if not github_token:
        print("Error: GITHUB_TOKEN environment variable required", file=sys.stderr)
        sys.exit(1)
    
    # Parse PR URL
    try:
        owner, repo, pr_number = parse_pr_url(args.pr)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    
    print(f"Fetching PR data for {owner}/{repo}#{pr_number}...", file=sys.stderr)
    
    # Fetch PR data
    try:
        pr_data = fetch_pr_data(owner, repo, pr_number, github_token)
    except requests.exceptions.RequestException as e:
        print(f"Error fetching PR data: {e}", file=sys.stderr)
        sys.exit(1)
    
    print("Analyzing with Claude...", file=sys.stderr)
    
    # Analyze with Claude
    try:
        analysis = analyze_with_claude(pr_data, api_key)
    except requests.exceptions.RequestException as e:
        print(f"Error calling Claude API: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Format output
    review = format_review(analysis, pr_data["url"])
    
    # Output
    if args.output:
        with open(args.output, "w") as f:
            f.write(review)
        print(f"Review saved to {args.output}", file=sys.stderr)
    else:
        print(review)


if __name__ == "__main__":
    main()